replicaCount: 1

image:
  repository: ghcr.io/platform-mesh/provider-quickstart
  pullPolicy: IfNotPresent
  tag: "@sha256:4a1c998e5f3d685071e929e4708f06207d477be7836cb96cda725f2b6410f12a"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Controller configuration
controller:
  endpointSlice: "wildwest.platform-mesh.io"

# kcp kubeconfig secret
kubeconfig:
  secretName: "wildwest-controller-kubeconfig"
  secretKey: "kubeconfig"
